name: paired-platoon
channels:
  - defaults
dependencies:
  - pip=21.1.2
  - python=3.8.10
  - pip:
    # - cloudpickle==1.6.0
    - gym==0.18.3
    - matplotlib==3.4.2
    - numpy==1.19.2
    - pandas==1.2.4
    - pygame==2.0.1
    - stable-baselines3==1.0
    - tensorboard==2.5.0
    # - torch==1.8.1
    - tqdm==4.60.0
    - onnx==1.9.0
    - onnx_tf==1.8.0
    # - tensorflow==2.5.0
    - boto3

# From PAIRED repo
    - cloudpickle~=1.2.0
    # - gym==0.15.7
    - gym-minigrid==1.0.1
    - networkx==2.5
    # numpy>=1.16.4
    # pandas>=1.0.5
    - torch~=1.7.0
    # matplotlib
    - seaborn
    - tensorflow==2.4.1
    - lempel_ziv_complexity
    # tqdm>=4.46.1
    # - gin-config==0.1.1 # error
    - cma==2.7.0
    - Box2D
    - pyglet<=1.5.0
    - pillow

    # I add:
    - minihack

    # Then go into trajectory env and do pip install -e .
